### ISSUE TITLE
Cannot update model: payload too large

### ISSUE THREAD

**Issue by srozga** [Microsoft/ConversationLearner-SDK#350]
I updated my CL recently, and I was asked to update the model. When I did, I got an error that the payload is too large. This is the same model I had shared with the team a bit ago. Thanks!

```
⚠ Local package upgraded to enable viewing.
⚪ Requested package id is the same the latest package id. This package is a candidate for saving.
⚠ Requested package id is also the live package id. Cannot safely auto upgrade. User must confirm in UI to save.
PayloadTooLargeError: request entity too large
    at readStream (C:\dev\learner\learner-bot-samples\node_modules\raw-body\index.js:155:17)
    at getRawBody (C:\dev\learner\learner-bot-samples\node_modules\raw-body\index.js:108:12)
    at read (C:\dev\learner\learner-bot-samples\node_modules\body-parser\lib\read.js:77:3)
    at jsonParser (C:\dev\learner\learner-bot-samples\node_modules\body-parser\lib\types\json.js:134:5)
    at Layer.handle [as handle_request] (C:\dev\learner\learner-bot-samples\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\dev\learner\learner-bot-samples\node_modules\express\lib\router\index.js:317:13)
    at C:\dev\learner\learner-bot-samples\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\dev\learner\learner-bot-samples\node_modules\express\lib\router\index.js:335:12)
    at next (C:\dev\learner\learner-bot-samples\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\dev\learner\learner-bot-samples\node_modules\express\lib\router\index.js:174:3)

```

**Comment by srozga** [comment]
I am indeed using the develop branch. I'll recreate some of these models to play with the latest. Thanks!
